# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [6]:
A = np.arange(1, 16).reshape(3,5)

In [8]:
print("Dimension (number of axes):", A.ndim)

print("Shape:", A.shape)

print("Size (total number of elements):", A.size)

print("Datatype:", A.dtype)

Dimension (number of axes): 2
Shape: (3, 5)
Size (total number of elements): 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [14]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print("Matris B:")
print(B)
print()

print("Matris C:")
print(C)
print()

print("E Subtraction:")
print(B - C)
print()

print("E Multiplication:")
print(B * C)
print()
# Samma som innan fast med multiplikation

print("Matrix Multiplication:")
print(B @ C)

Matris B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matris C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

E Subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

E Multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [22]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

exp_B = np.exp(B)
print("Exponentiate each element:")
print(exp_B)
print()

# minst i matrisen
min_val = B.min()
print("Minimum value in the whole matrix:")
print(min_val)
print()

# minst i varje rad
min_row = B.min(axis=1)
print("Minimum value in each row:")
print(min_row)
print()

# minsta i varje kolumn
min_col = B.min(axis=0)
print("Minimum value in each column:")
print(min_col)
print()

# 5. Index för det minsta värdet i hela matrisen.
argmin_val = np.argmin(B)
print("Index for the minimum value in the whole matrix:")
print(argmin_val)
print()

# returnerartill 0
argmin_row = np.argmin(B, axis=1)
print("Index for the minimum value in each row:")
print(argmin_row)
print()

# 7. Summan av elementen (adderad)
sum_all = B.sum()
print("Sum of all elements:")
print(sum_all)
print()

# 8. Medelvärde för varje kolumn (man delar alla kolumner)
mean_col = B.mean(axis=0)
print("Mean for each column:")
print(mean_col)
print()

# Median för varje kolumn (allt imellan)
median_col = np.median(B, axis=0)
print("Median for each column:")
print(median_col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Exponentiate each element:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix:
1

Minimum value in each row:
[1 4 7]

Minimum value in each column:
[1 2 3]

Index for the minimum value in the whole matrix:
0

Index for the minimum value in each row:
[0 0 0]

Sum of all elements:
45

Mean for each column:
[4. 5. 6.]

Median for each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [ ]:
#Anger man färre index än matrisens dimensioner, fås en hel rad, kolumn eller del, t.ex ger A[1] hela andra raden.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [24]:
A= np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [26]:
for i in A:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [28]:
for element in np.nditer(A):
    print(element)

1
2
3
4
5
6
7
8
9


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

In [ ]:
#Arrayen A är tredimensionell med tre axlar: block (första axeln), rader (andra axeln) och kolumner (tredje axeln).

In [ ]:
#Reshape skapar en tredimensionell array med data organiserad i block, rader och kolumner.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [30]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

#SVAR: Det fungerar tack vare broadcasting, där m2 expanderas för att matcha m1:s storlek.

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [32]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

#SVAR: Broadcasting i NumPy ändrar automatiskt 1 till v1:s storlek, vilket förenklar additionen.

[2 3 4]


In [36]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

#SVAR: A är en array med siffrorna 1–4 som formas till en 2x2-matris, och B är en enradig array. Sedan kan jag utföra operationer som addition, subtraktion eller multiplikation.

print("A + b:")
print(A + b)

print("A - b:")
print(A - b)

print("A * b:")
print(A * b)

[[1 2]
 [3 4]]
[2 2]
A + b:
[[3 4]
 [5 6]]
A - b:
[[-1  0]
 [ 1  2]]
A * b:
[[2 4]
 [6 8]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [42]:
import numpy as np

def add_mult_matrices(matris1, matris2, operation):
 
    
 
    # Kontrollera att båda är numpy-matriser
    if not isinstance(matris1, np.ndarray) or not isinstance(matris2, np.ndarray):
        raise TypeError("Matriserna ska vara numpy.ndarray")
    
    # Kontrollera att operationen är 'add' eller 'multiply'
    if operation not in ['add', 'multiply']:
        raise ValueError("Endast 'add' eller 'multiply' är tillåtna")
    
    if operation == 'add':
        # Kontrollera att matriserna är lika stora
        if matris1.shape != matris2.shape:
            raise ValueError("För addition måste matriserna ha samma storlek")
        return matris1 + matris2  # Addera matriser
    
    elif operation == 'multiply':
        # Kontrollera att dimensionerna stämmer överns
        if matris1.shape[1] != matris2.shape[0]:
            raise ValueError("För multiplikation måste kolumner i matris1 matcha rader i matris2")
        return np.dot(matris1, matris2)  # Multiplicera matriser



matris1 = np.array([[1, 2], [3, 4]])
matris2 = np.array([[5, 6], [7, 8]])

print("Addition:\n", add_mult_matrices(matris1, matris2, 'add'))
print("\n")
print("Multiplikation:\n", add_mult_matrices(matris1, matris2, 'multiply'))

Addition:
 [[ 6  8]
 [10 12]]


Multiplikation:
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [44]:
import numpy as np

x = np.array([4, 3])

print("A Svar:")
# Dimension
dimension = x.shape
print("Dimension är:", dimension)

print("\n B Svar:")
# Beräkna 5x
result = 5 * x
print("Resultatet av 5x är:", result)

print("\n C Svar:")
# Beräkna 3x
result = 3 * x
print("Resultatet av 3x är:", result)

print("\n D Svar:")
# Beräkna 5x + 3x
result = 5 * x + 3 * x
print("Resultatet av 5x + 3x är:", result)

print("\n E Svar:")
# Beräkna 8x
result = 8 * x
print("Resultatet av 8x är:", result,)

print("\n F Svar:")
# Beräkna 4x - x
result = 4 * x - x
print("Resultatet av 4x - x är:", result)


print("\n G Svar:")
x_transposed = x.T  # transponeringen
dimension = x_transposed.shape # nya dimensionen
print("Ny dimension:", dimension)

print("\n H Svar:")
x_transposed = x.T
try:
    result = x + x_transposed
    print("Resultatet av x + x^T är:\n", result)
except ValueError as e:
    print("x + x^T är inte definierat. Felmeddelande:", e)

print("\n I Svar:")
norm = np.linalg.norm(x)
print("Normen är:", norm)

print("\n Uppgift 10.1.2:")
print("\n A Svar:")

v = np.array([3, 7, 0, 11])
dimension = v.shape  

print(f"Dimensionen av vektorn v är: {dimension}")

print("\n B Svar:")

result = 2 * v

print(f"2v = {result}")

print("\n C Svar:")

result = 5 * v + 2 * v

print(f"5v + 2v = {result}")

print("\n D Svar:")

result = 4 * v - 2 * v

print(f"5v - 2v = {result}")

print("\n E Svar:")

v_transposed = v.reshape(-1, 1)  # Göra om vektorn till en kolumn
new_dimension = v_transposed.shape

print(v_transposed, new_dimension)

print("\n F Svar:")

norm_v = np.linalg.norm(v)

print(norm_v)

print("\n Uppgift 10.1.3:")
print("\n A Svar:")

#vektor v1
v1 = np.array([4, 3, 1, 5])

#normen av v1
norm_v1 = np.linalg.norm(v1)

print(norm_v1)

print("\n B Svar:")

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# Skillnaden v1 - v2
difference = v1 - v2

norm_difference = np.linalg.norm(difference)

print(norm_difference)

A Svar:
Dimension är: (2,)

 B Svar:
Resultatet av 5x är: [20 15]

 C Svar:
Resultatet av 3x är: [12  9]

 D Svar:
Resultatet av 5x + 3x är: [32 24]

 E Svar:
Resultatet av 8x är: [32 24]

 F Svar:
Resultatet av 4x - x är: [12  9]

 G Svar:
Ny dimension: (2,)

 H Svar:
Resultatet av x + x^T är:
 [8 6]

 I Svar:
Normen är: 5.0

 Uppgift 10.1.2:

 A Svar:
Dimensionen av vektorn v är: (4,)

 B Svar:
2v = [ 6 14  0 22]

 C Svar:
5v + 2v = [21 49  0 77]

 D Svar:
5v - 2v = [ 6 14  0 22]

 E Svar:
[[ 3]
 [ 7]
 [ 0]
 [11]] (4, 1)

 F Svar:
13.379088160259652

 Uppgift 10.1.3:

 A Svar:
7.14142842854285

 B Svar:
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [46]:
print("\n Uppgift 10.2.1:")
print("\n A Svar:")
A = np.array([[2, 1, -1],
              [1, -1, 1]])

result_2A = 2 * A

print(result_2A)

print("\n B Svar:")
A = np.array([[2, 1, -1],
              [1, -1, 1]])
B = np.array([[4, -2, 1],
              [2, -4, -2]])

result_B_minus_2A = B - 2 * A

print(result_B_minus_2A)

print("\n C Svar:")

C = np.array([[1, 2],
              [2, 1]])
E = np.array([[1],
              [2]])


result_3C_minus_2E = 3 * C - 2 * E

print(result_3C_minus_2E)

print("\n D Svar:")

C = np.array([[1, 2],
              [2, 1]])
D = np.array([[3, 4],
              [4, 3]])


result_2D_minus_3C = 2 * D - 3 * C

print(result_2D_minus_3C)


print("\n E Svar:")

D_transposed_plus_2D = D.T + 2 * D

print(D_transposed_plus_2D)


print("\n F Svar:")


result_2C_T_minus_2D_T = 2 * C.T - 2 * D.T

print(result_2C_T_minus_2D_T)


print("\n G Svar:")

#result_A_T_minus_B = A.T - B

#print(result_A_T_minus_B)

print("Dimensionerna för At och B överensstämmer inte, vilket gör subtraktionen omöjlig utan att justera matriserna.")

print("\n H Svar:")


print("Multiplikationen AC är inte möjligt eftersom antal kolumner i A inte matcher antalet rader i C.")

print("\n I Svar:")


result_CD = np.dot(C, D)

print(result_CD)


print("\n J Svar:")

result_CB = np.dot(C, B)

print(result_CB)


print("\n K Svar:")

I = np.array([[1, 0],
              [0, 1]])

result_CI = np.dot(C, I)

print(result_CI)


print("\n L Svar:")

result_AB_T = np.dot(A, B.T)

print(result_AB_T)



 Uppgift 10.2.1:

 A Svar:
[[ 4  2 -2]
 [ 2 -2  2]]

 B Svar:
[[ 0 -4  3]
 [ 0 -2 -4]]

 C Svar:
[[ 1  4]
 [ 2 -1]]

 D Svar:
[[3 2]
 [2 3]]

 E Svar:
[[ 9 12]
 [12  9]]

 F Svar:
[[-4 -4]
 [-4 -4]]

 G Svar:
Dimensionerna för At och B överensstämmer inte, vilket gör subtraktionen omöjlig utan att justera matriserna.

 H Svar:
Multiplikationen AC är inte möjligt eftersom antal kolumner i A inte matcher antalet rader i C.

 I Svar:
[[11 10]
 [10 11]]

 J Svar:
[[  8 -10  -3]
 [ 10  -8   0]]

 K Svar:
[[1 2]
 [2 1]]

 L Svar:
[[5 2]
 [7 4]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [48]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

v2[-1] = 123
print(v1)  
print(v2)  

print ("Eftersom v2 är en vy av v1, kommer ändringen i v2 att reflekteras i v1. Därför ändras det sista elementet i v1 också till 123")


[0 1 2 3]
[2 3]
[  0   1   2 123]
[  2 123]
Eftersom v2 är en vy av v1, kommer ändringen i v2 att reflekteras i v1. Därför ändras det sista elementet i v1 också till 123


In [50]:
# The base attribute of a view returns the original array while it returns None for a copy.
v1 = np.arange(4)
v2 = v1[-2:]

print(v1.base)
print(v2.base)

print("v1.base är None eftersom v1 är originalet och inte en vy.")
print("v2.base pekar på v1 eftersom v2 är en vy av v1 och delar data.")

None
[0 1 2 3]
v1.base är None eftersom v1 är originalet och inte en vy.
v2.base pekar på v1 eftersom v2 är en vy av v1 och delar data.


In [52]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

print("Eftersom v2 är en vy av v1, delar de samma data.")
print("När man ändrar det sista elementet i v2, ändras också motsvarande element i v1.")

[  0   1   2 123]
[  2 123]
Eftersom v2 är en vy av v1, delar de samma data.
När man ändrar det sista elementet i v2, ändras också motsvarande element i v1.
